/**
 * Initial Realistic Luxury Hotel Bar Dataset for TUI BLUE
 * Provides working Unsplash images, full 4-language translations, and configurable single-currency pricing (TRY or USD).
 */

export const mockCategories = [
  {
    id: 'cat-01-signature',
    name_tr: 'İmza Kokteyller',
    name_en: 'Signature Cocktails',
    name_ru: 'Фирменные коктейли',
    name_de: 'Signatur-Cocktails',
    icon: 'Sparkles',
    sort_order: 1,
  },
  {
    id: 'cat-02-classics',
    name_tr: 'Klasik Kokteyller',
    name_en: 'Classic Cocktails',
    name_ru: 'Классические коктейли',
    name_de: 'Klassische Cocktails',
    icon: 'GlassWater',
    sort_order: 2,
  },
  {
    id: 'cat-03-whiskey',
    name_tr: 'Viski & Single Malt',
    name_en: 'Whiskey & Single Malts',
    name_ru: 'Виски и Односолодовые',
    name_de: 'Whiskey & Single Malts',
    icon: 'Flame',
    sort_order: 3,
  },
  {
    id: 'cat-04-gin',
    name_tr: 'Cin & Tonik',
    name_en: 'Gin & Botanicals',
    name_ru: 'Джин и Тоник',
    name_de: 'Gin & Botanicals',
    icon: 'Citrus',
    sort_order: 4,
  },
  {
    id: 'cat-05-wine',
    name_tr: 'Şarap & Şampanya',
    name_en: 'Wine & Champagne',
    name_ru: 'Вино и Шампанское',
    name_de: 'Wein & Champagner',
    icon: 'Wine',
    sort_order: 5,
  },
  {
    id: 'cat-06-beer',
    name_tr: 'Bira Çeşitleri',
    name_en: 'Craft & Draught Beers',
    name_ru: 'Пиво',
    name_de: 'Biere vom Fass & Flaschen',
    icon: 'Beer',
    sort_order: 6,
  },
  {
    id: 'cat-07-mocktail',
    name_tr: 'Mocktail & Alkolsüz',
    name_en: 'Mocktails & Non-Alcoholic',
    name_ru: 'Безалкогольные коктейли',
    name_de: 'Alkoholfreie Mocktails',
    icon: 'HeartHandshake',
    sort_order: 7,
  },
  {
    id: 'cat-08-hot',
    name_tr: 'Sıcak İçecekler & Kahve',
    name_en: 'Artisanal Teas & Coffee',
    name_ru: 'Горячие напитки и кофе',
    name_de: 'Kaffee & Teespezialitäten',
    icon: 'Coffee',
    sort_order: 8,
  },
];

export const mockMenuItems = [
  // 1. Signature Cocktails
  {
    id: 'item-01',
    category_id: 'cat-01-signature',
    title_tr: 'TUI BLUE Sunset',
    title_en: 'TUI BLUE Sunset',
    title_ru: 'Закат ТУИ БЛЮ',
    title_de: 'TUI BLUE Sunset',
    description_tr: 'Mürver çiçeği likörü, taze çarkıfelek meyvesi püresi, prosecco ve altın simli narenciye infüzyonu.',
    description_en: 'Elderflower liqueur, fresh passionfruit purée, crisp prosecco topped with 24k gold shimmer citrus spray.',
    description_ru: 'Ликер бузины, пюре из свежей маракуйи, просекко с золотым цитрусовым напылением 24k.',
    description_de: 'Holunderblütenlikör, frisches Maracujapüree, spritziger Prosecco mit 24k Goldstaub-Zitrusaroma.',
    price: 650,
    currency: 'TRY',
    volume_ml: 200,
    abv: 12.5,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    previous_image_url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
    is_available: true,
    tags: ['Signature', 'Fruity', 'Gold', 'Sunset'],
    created_at: '2026-01-10T12:00:00Z',
  },
  {
    id: 'item-02',
    category_id: 'cat-01-signature',
    title_tr: 'Smoked Amber Old Fashioned',
    title_en: 'Smoked Amber Old Fashioned',
    title_ru: 'Копченый янтарный Олд Фэшн',
    title_de: 'Geräucherter Bernstein Old Fashioned',
    description_tr: 'Meşe fıçıda dinlendirilmiş burbon, akçaağaç şurubu, angostura bitter ve sedir ağacı dumanı.',
    description_en: 'Oak-barrel rested Kentucky bourbon, artisanal maple reduction, aromatic bitters infused with smoked cedar.',
    description_ru: 'Выдержанный в дубе бурбон, кленовый сироп, ароматические биттеры и дым кедровой щепы.',
    description_de: 'Im Eichenfass gereifter Kentucky Bourbon, Ahornsirup, aromatische Bitter mit Zedernholzrauch.',
    price: 670,
    currency: 'TRY',
    volume_ml: 120,
    abv: 32.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Signature', 'Smoky', 'Strong'],
    created_at: '2026-01-11T14:30:00Z',
  },
  {
    id: 'item-03',
    category_id: 'cat-01-signature',
    title_tr: 'Aegean Blue Velvet',
    title_en: 'Aegean Blue Velvet',
    title_ru: 'Эгейский Голубой Бархат',
    title_de: 'Ägäischer Blauer Samt',
    description_tr: 'Kelebek bezelye çiçeği infüze cin, lavanta şurubu, taze Amalfi limonu ve Fever-Tree tonik.',
    description_en: 'Butterfly pea blossom infused gin, botanical lavender syrup, fresh Amalfi lemon, Fever-Tree tonic.',
    description_ru: 'Джин, настоянный на цветках анчана, лавандовый сироп, лимонный сок и тоник.',
    description_de: 'Mit Schmetterlingserbsenblüten infundierter Gin, Lavendelsirup, Amalfi-Zitrone, Premium-Tonic.',
    price: 580,
    currency: 'TRY',
    volume_ml: 220,
    abv: 14.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Botanical', 'Floral', 'Color Changing'],
    created_at: '2026-01-12T16:00:00Z',
  },

  // 2. Classics
  {
    id: 'item-04',
    category_id: 'cat-02-classics',
    title_tr: 'Espresso Martini Royale',
    title_en: 'Espresso Martini Royale',
    title_ru: 'Эспрессо Мартини Рояль',
    title_de: 'Espresso Martini Royale',
    description_tr: 'Taze çekilmiş tek kökenli espresso, vanilyalı votka, Kahlúa kahve likörü ve çikolata tozu.',
    description_en: 'Single origin freshly pulled espresso, vanilla-infused vodka, Kahlúa coffee liqueur, dark cacao dust.',
    description_ru: 'Свежесваренный эспрессо, ванильная водка, кофейный ликер Kahlúa и темный какао.',
    description_de: 'Frisch gebrühter Espresso, Vanille-Wodka, Kahlúa-Kaffeelikör, Zartbitter-Kakaostaub.',
    price: 540,
    currency: 'TRY',
    volume_ml: 150,
    abv: 18.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1545438102-799c3991ffb2?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Classic', 'Coffee', 'Rich'],
    created_at: '2026-01-13T10:00:00Z',
  },
  {
    id: 'item-05',
    category_id: 'cat-02-classics',
    title_tr: 'Negroni Classico',
    title_en: 'Negroni Classico',
    title_ru: 'Негрони Классико',
    title_de: 'Negroni Classico',
    description_tr: 'Tanqueray No. Ten cin, Campari ve Antica Formula tatlı vermut, alevlendirilmiş portakal kabuğu.',
    description_en: 'Tanqueray No. Ten gin, bitter Campari, Carpano Antica Formula sweet vermouth, flamed orange peel.',
    description_ru: 'Джин Tanqueray No. Ten, биттер Campari, красный вермут Antica Formula, цедра апельсина.',
    description_de: 'Tanqueray No. Ten Gin, Campari, roter Wermut Antica Formula mit flambierter Orangenzeste.',
    price: 16.00,
    currency: 'USD',
    volume_ml: 110,
    abv: 24.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Classic', 'Bitter-Sweet', 'Aperitif'],
    created_at: '2026-01-14T11:00:00Z',
  },
  {
    id: 'item-06',
    category_id: 'cat-02-classics',
    title_tr: 'French 75 Luxury',
    title_en: 'French 75 Champagne Cocktail',
    title_ru: 'Френч 75 с Шампанским',
    title_de: 'French 75 Champagner-Cocktail',
    description_tr: 'Hendrick’s cin, taze limon suyu, şeker şurubu ve Moët & Chandon şampanya.',
    description_en: 'Artisanal gin, freshly squeezed lemon juice, simple syrup, topped with Moët & Chandon Champagne.',
    description_ru: 'Джин, лимонный сок, сахарный сироп и шампанское Moët & Chandon.',
    description_de: 'Gin, frischer Zitronensaft, Zuckersirup, verfeinert mit Moët & Chandon Champagner.',
    price: 17.50,
    currency: 'USD',
    volume_ml: 160,
    abv: 15.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1578664182354-e3879d36d90e?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: false, // Stop-list test item
    tags: ['Champagne', 'Crisp', 'Celebration'],
    created_at: '2026-01-15T15:00:00Z',
  },

  // 3. Whiskey & Single Malts
  {
    id: 'item-07',
    category_id: 'cat-03-whiskey',
    title_tr: 'Macallan 12 Yıllık Double Cask',
    title_en: 'Macallan 12 Years Double Cask',
    title_ru: 'Макаллан 12 Лет Дабл Каск',
    title_de: 'Macallan 12 Jahre Double Cask',
    description_tr: 'Sherry fıçılarda olgunlaşmış dengeli vanilya, zencefil ve kuru meyve notaları.',
    description_en: 'Aged in hand-picked sherry-seasoned oak casks. Balanced notes of honey, delicate spice, and dried fruits.',
    description_ru: 'Выдержан в дубовых бочках из-под хереса. Ноты меда, имбиря и сухофруктов.',
    description_de: 'Gereift in handverlesenen Sherryfässern. Aromen von Honig, edlen Gewürzen und getrockneten Früchten.',
    price: 22.00,
    currency: 'USD',
    volume_ml: 50,
    abv: 40.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Single Malt', 'Speyside', 'Luxury'],
    created_at: '2026-01-16T18:00:00Z',
  },
  {
    id: 'item-08',
    category_id: 'cat-03-whiskey',
    title_tr: 'Lagavulin 16 Yıllık Islay Malt',
    title_en: 'Lagavulin 16 Years Single Islay Malt',
    title_ru: 'Лагавулин 16 Лет',
    title_de: 'Lagavulin 16 Jahre Single Islay Malt',
    description_tr: 'Yoğun turba dumanı, deniz yosunu ve zengin meyvemsi meşe karakteri.',
    description_en: 'Intense peaty smoke, maritime iodine, sweet rich dried fruit and long spicy finish.',
    description_ru: 'Насыщенный торфяной дым, морские ноты, богатые сладкие сухофрукты.',
    description_de: 'Intensiver Torfrauch, Meeresaromen, reife Trockenfrüchte und ein langanhaltender Abgang.',
    price: 25.00,
    currency: 'USD',
    volume_ml: 50,
    abv: 43.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Single Malt', 'Islay', 'Peated'],
    created_at: '2026-01-17T19:00:00Z',
  },

  // 4. Gin & Botanicals
  {
    id: 'item-09',
    category_id: 'cat-04-gin',
    title_tr: 'Hendrick’s Botanical Tonic',
    title_en: 'Hendrick’s Botanical Tonic',
    title_ru: 'Хендрикс Ботаникал Тоник',
    title_de: 'Hendrick’s Botanical Tonic',
    description_tr: 'Gül yaprakları ve salatalık esansı ile damıtılmış cin, taze salatalık şeridi ve pembe karabiber ile.',
    description_en: 'Infused with rose and crisp cucumber, garnished with ribbons of English cucumber and pink peppercorns.',
    description_ru: 'Джин с экстрактом розы и огурца, подается с ломтиком огурца и розовым перцем.',
    description_de: 'Destilliert mit Rosen- und Gurkenessenzen, serviert mit Gurkenstreifen und rosa Pfefferkörnern.',
    price: 580,
    currency: 'TRY',
    volume_ml: 250,
    abv: 13.5,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1607622750671-6cd9a99eabd1?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Gin', 'Refreshing', 'Cucumber'],
    created_at: '2026-01-18T14:00:00Z',
  },
  {
    id: 'item-10',
    category_id: 'cat-04-gin',
    title_tr: 'Monkey 47 Schwarzwald Gin',
    title_en: 'Monkey 47 Schwarzwald Dry Gin',
    title_ru: 'Манки 47 Шварцвальд Джин',
    title_de: 'Monkey 47 Schwarzwald Dry Gin',
    description_tr: 'Kara Orman’dan 47 farklı botanik, ardıç, yabani böğürtlen ve narenciye patlaması.',
    description_en: '47 handpicked botanicals from the Black Forest, lingonberries, cranberries, herbal depth.',
    description_ru: '47 растительных компонентов из Шварцвальда, брусника, клюква и глубокий травяной букет.',
    description_de: '47 handverlesene Botanicals aus dem Schwarzwald, Preiselbeeren, Kräutertiefe.',
    price: 735,
    currency: 'TRY',
    volume_ml: 250,
    abv: 16.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Gin', 'Black Forest', 'Premium'],
    created_at: '2026-01-19T15:00:00Z',
  },

  // 5. Wine & Champagne
  {
    id: 'item-11',
    category_id: 'cat-05-wine',
    title_tr: 'Moët & Chandon Impérial Brut',
    title_en: 'Moët & Chandon Impérial Brut',
    title_ru: 'Моэт и Шандон Империал Брют',
    title_de: 'Moët & Chandon Impérial Brut',
    description_tr: 'Fransız şampanyası; canlı yeşil elma, narenciye ve taze briyoş aromaları.',
    description_en: 'The world’s most loved champagne: vibrant green apple, citrus zest, and elegant mineral nuances.',
    description_ru: 'Легендарное французское шампанское: хрустящее зеленое яблоко, цитрусовые и легкая минеральность.',
    description_de: 'Der beliebteste Champagner der Welt: grüner Apfel, Zitrusfrische und elegante Brioche-Noten.',
    price: 95.00,
    currency: 'USD',
    volume_ml: 750,
    abv: 12.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Champagne', 'Brut', 'Bottle'],
    created_at: '2026-01-20T16:00:00Z',
  },
  {
    id: 'item-12',
    category_id: 'cat-05-wine',
    title_tr: 'Whispering Angel Côtes de Provence Rosé',
    title_en: 'Whispering Angel Côtes de Provence Rosé',
    title_ru: 'Шепчущий Ангел Прованс Розе',
    title_de: 'Whispering Angel Côtes de Provence Rosé',
    description_tr: 'Provence bölgesinden ipeksi pembe şarap, kırmızı meyve ve taze çiçek dokunuşları.',
    description_en: 'Premium Provence rosé wine with silky red berry aromas, peach blossom, and a crisp flinty finish.',
    description_ru: 'Премиальное розовое вино из Прованса: шелковистые красные ягоды, цветки персика и минеральность.',
    description_de: 'Erstklassiger Roséwein aus der Provence mit Aromen von roten Beeren, Pfirsichblüten und Frische.',
    price: 1680,
    currency: 'TRY',
    volume_ml: 750,
    abv: 13.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Wine', 'Rose', 'Provence'],
    created_at: '2026-01-21T17:00:00Z',
  },

  // 6. Beers
  {
    id: 'item-13',
    category_id: 'cat-06-beer',
    title_tr: 'Stella Artois Fıçı',
    title_en: 'Stella Artois Draught Pilsner',
    title_ru: 'Стелла Артуа Разливное',
    title_de: 'Stella Artois Fassbier',
    description_tr: 'Belçika usulü berrak pilsner, saaz şerbetçiotu aroması ve ferahlatıcı dengeli bitiş.',
    description_en: 'Belgian premium lager with Saaz hops, floral aroma, crisp clean finish served in chalice.',
    description_ru: 'Бельгийский светлый лагер с хмелем Saaz, цветочными нотами и чистым послевкусием.',
    description_de: 'Belgisches Premium-Pilsner mit Saazer Hopfen, floralem Aroma und frischem Abgang.',
    price: 300,
    currency: 'TRY',
    volume_ml: 500,
    abv: 5.0,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1608270195655-3b983d95eb87?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Beer', 'Draught', 'Lager'],
    created_at: '2026-01-22T12:00:00Z',
  },
  {
    id: 'item-14',
    category_id: 'cat-06-beer',
    title_tr: 'Paulaner Hefe-Weißbier',
    title_en: 'Paulaner Hefe-Weißbier Naturtrüb',
    title_ru: 'Пауланер Хефе-Вайсбир',
    title_de: 'Paulaner Hefe-Weißbier Naturtrüb',
    description_tr: 'Geleneksel Münih buğday birası; muz, karanfil ve hafif narenciye tatları.',
    description_en: 'Classic unfiltered Bavarian wheat beer with subtle banana, clove, and silky foam head.',
    description_ru: 'Классическое нефильтрованное баварское пшеничное пиво с нотами банана и гвоздики.',
    description_de: 'Klassisches ungefiltertes bayerisches Weißbier mit feinen Bananen- und Nelkennoten.',
    price: 315,
    currency: 'TRY',
    volume_ml: 500,
    abv: 5.5,
    is_alcoholic: true,
    current_image_url: 'https://images.unsplash.com/photo-1618183479302-1e0aa382c36b?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Beer', 'Wheat', 'Bavaria'],
    created_at: '2026-01-23T13:00:00Z',
  },

  // 7. Mocktails & Non-Alcoholic
  {
    id: 'item-15',
    category_id: 'cat-07-mocktail',
    title_tr: 'Virgin Passionfruit & Rosemary Fizz',
    title_en: 'Virgin Passionfruit & Rosemary Fizz',
    title_ru: 'Маракуйя и Розмарин Физз (Безалкогольный)',
    title_de: 'Virgin Maracuja & Rosmarin Fizz',
    description_tr: 'Taze çarkıfelek meyvesi, dağ kekiği şurubu, alevlendirilmiş taze biberiye ve maden suyu.',
    description_en: 'Fresh passionfruit pulp, artisanal rosemary syrup, crushed ice, and sparkling mineral water.',
    description_ru: 'Свежая маракуйя, сироп розмарина, колотый лед и газированная минеральная вода.',
    description_de: 'Frische Maracuja, Rosmarinsirup, Crushed Ice und prickelndes Mineralwasser.',
    price: 330,
    currency: 'TRY',
    volume_ml: 300,
    abv: 0.0,
    is_alcoholic: false,
    current_image_url: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Mocktail', 'Non-Alcoholic', 'Refreshing', 'Virgin'],
    created_at: '2026-01-24T14:00:00Z',
  },
  {
    id: 'item-16',
    category_id: 'cat-07-mocktail',
    title_tr: 'Cranberry Basil Elixir',
    title_en: 'Cranberry Basil Elixir',
    title_ru: 'Клюквенно-базиликовый эликсир',
    title_de: 'Cranberry-Basilikum-Elixier',
    description_tr: 'Organik turna yemişi suyu, taze fesleğen yaprakları, misket limonu ve zencefilli gazoz.',
    description_en: 'Wild tart cranberry juice, muddled Italian basil leaves, cold-pressed lime, ginger ale.',
    description_ru: 'Дикая клюква, свежий итальянский базилик, сок лайма и имбирный эль.',
    description_de: 'Wilder Cranberrysaft, frischer Basilikum, Limette und Ginger Ale.',
    price: 315,
    currency: 'TRY',
    volume_ml: 280,
    abv: 0.0,
    is_alcoholic: false,
    current_image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Mocktail', 'Non-Alcoholic', 'Herbal'],
    created_at: '2026-01-25T15:00:00Z',
  },

  // 8. Hot Beverages & Coffee
  {
    id: 'item-17',
    category_id: 'cat-08-hot',
    title_tr: 'Damla Sakızlı Türk Kahvesi',
    title_en: 'Artisanal Turkish Mastic Coffee',
    title_ru: 'Турецкий кофе с мастикой',
    title_de: 'Traditioneller Türkischer Mokka mit Mastix',
    description_tr: 'Özel çekilmiş bakır cezvede pişirilen geleneksel damla sakızlı Türk kahvesi, lokum eşliğinde.',
    description_en: 'Slow-brewed in copper cezve over hot sand, infused with Chios mastic gum, served with lokum.',
    description_ru: 'Сваренный на песке турецкий кофе с натуральной мастикой, подается с рахат-лукумом.',
    description_de: 'Im Kupferkännchen auf heißem Sand zubereiteter Mokka mit Mastix, serviert mit Lokum.',
    price: 230,
    currency: 'TRY',
    volume_ml: 80,
    abv: 0.0,
    is_alcoholic: false,
    current_image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Coffee', 'Traditional', 'Hot'],
    created_at: '2026-01-26T10:00:00Z',
  },
  {
    id: 'item-18',
    category_id: 'cat-08-hot',
    title_tr: 'Kakuleli Flat White',
    title_en: 'Smoked Cardamom Flat White',
    title_ru: 'Флэт Уайт с кардамоном',
    title_de: 'Geräucherter Kardamom Flat White',
    description_tr: 'Çift shot espresso, mikro köpürtülmüş süt, kavrulmuş kakule tozu.',
    description_en: 'Double shot specialty espresso, silky micro-foamed milk, dusting of freshly ground cardamom.',
    description_ru: 'Двойной эспрессо, шелковистая микропенка молока и щепотка свежего кардамона.',
    description_de: 'Doppelter Espresso, samtiger Mikroschaum und ein Hauch frisch gemahlener Kardamom.',
    price: 260,
    currency: 'TRY',
    volume_ml: 200,
    abv: 0.0,
    is_alcoholic: false,
    current_image_url: 'https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=800&q=80',
    previous_image_url: null,
    is_available: true,
    tags: ['Coffee', 'Barista', 'Hot'],
    created_at: '2026-01-27T11:00:00Z',
  },
];
