/**
 * Generates supabase/seed.sql from src/utils/mockData.js so the hosted
 * database starts with exactly the same 4 categories and all beverages.
 * Usage: npm run db:seed  (then paste supabase/seed.sql into Supabase SQL Editor)
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { mockCategories, mockMenuItems } from '../src/utils/mockData.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(__dirname, '../supabase');
const outFile = path.join(outDir, 'seed.sql');

const q = (v) => {
  if (v === null || v === undefined || v === '') return 'NULL';
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE';
  if (typeof v === 'number') return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (a) =>
  Array.isArray(a) && a.length ? `ARRAY[${a.map(q).join(', ')}]::TEXT[]` : `'{}'::TEXT[]`;

const lines = [
  '-- AUTO-GENERATED by scripts/generate-seed.mjs. Do not edit by hand.',
  '-- Run AFTER schema.sql. Safe to re-run: existing rows are replaced.',
  'BEGIN;',
  'DELETE FROM menu_items;',
  'DELETE FROM categories;',
  '',
  'INSERT INTO categories (id, name_en, name_tr, name_de, name_ru, icon, sort_order) VALUES',
  mockCategories
    .map(
      (c) =>
        `  (${q(c.id)}, ${q(c.name_en)}, ${q(c.name_tr)}, ${q(c.name_de)}, ${q(c.name_ru)}, ${q(c.icon)}, ${q(c.sort_order)})`
    )
    .join(',\n') + ';',
  '',
  'INSERT INTO menu_items (category_id, subcategory, title_en, title_tr, title_de, title_ru, description_en, description_tr, description_de, description_ru, price, currency, is_alcoholic, is_featured, is_signature, is_extra, is_available, current_image_url, tags, sort_order) VALUES',
  mockMenuItems
    .map(
      (i, idx) =>
        `  (${[
          q(i.category_id),
          q(i.subcategory),
          q(i.title_en),
          q(i.title_tr),
          q(i.title_de),
          q(i.title_ru),
          q(i.description_en),
          q(i.description_tr),
          q(i.description_de),
          q(i.description_ru),
          q(Number(i.price) || 0),
          q(i.currency || 'EUR'),
          q(Boolean(i.is_alcoholic)),
          q(Boolean(i.is_featured)),
          q(Boolean(i.is_signature)),
          q(Boolean(i.is_extra)),
          q(i.is_available !== false),
          q(i.current_image_url),
          arr(i.tags),
          q(i.sort_order ?? idx + 1),
        ].join(', ')})`
    )
    .join(',\n') + ';',
  '',
  'COMMIT;',
  '',
];

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log(`Wrote ${mockCategories.length} categories and ${mockMenuItems.length} items to ${outFile}`);
